# Simple DialogChain Configuration
routes:
  - name: hello_world
    from: http://0.0.0.0:8000/hello
    to: log:info
    processors:
      - type: transform
        template: '{"message": "Hello, World!"}'
