# Simple DialogChain Configuration
routes:
  - name: hello_world
    source:
      type: http
      endpoint: /hello
      method: GET
    processors:
      - type: transform
        template: '{"message": "Hello, World!"}'
    sink:
      type: http_response
      content_type: application/json
