name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for version tagging
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-venv

    - name: Install Poetry
      run: |
        pip install "poetry==1.5.1"
        echo "$(python -m site --user-base)/bin" >> $GITHUB_PATH
    
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
        poetry config --list
        poetry --version
    
    - name: Install dependencies
      run: |
        # Check for lock file and generate if needed
        if [ ! -f poetry.lock ]; then
          echo "No poetry.lock found, generating one..."
          # First install without lock file to resolve dependencies
          poetry install --no-dev --no-interaction --no-ansi -v --no-root
          # Then generate the lock file
          poetry lock --no-update
        fi
        
        # Install dependencies with the lock file
        echo "Installing dependencies..."
        poetry install --no-dev --no-interaction --no-ansi -v
        
        # Show environment info for debugging
        poetry env info
        echo "Installed packages:"
        poetry show --tree
    
    - name: Build and publish
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        # Configure PyPI token
        poetry config pypi-token.pypi $PYPI_TOKEN
        
        # Build and publish
        poetry build -v
        poetry publish --no-interaction -v
