name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for version tagging
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-venv

    - name: Install Poetry
      run: |
        pip install "poetry==1.5.1"
        echo "$(python -m site --user-base)/bin" >> $GITHUB_PATH
    
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
        poetry config --list
        poetry --version
    
    - name: Install dependencies
      run: |
        # Generate lock file if it doesn't exist
        if [ ! -f poetry.lock ]; then
          echo "No poetry.lock found, generating one..."
          poetry lock --no-update
        fi
        
        # Install dependencies
        poetry install --no-dev --no-interaction --no-ansi -v
        poetry env info
    
    - name: Build and publish
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        # Configure PyPI token
        poetry config pypi-token.pypi $PYPI_TOKEN
        
        # Build and publish
        poetry build -v
        poetry publish --no-interaction -v
